// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TryCodeReview from "./try_code_review"
application.register("try_code_review", TryCodeReview)
